name: Wheel build

on:
  release:
    types: [created]
  push:

jobs:
  non-Linux:
    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      matrix:
        os: [macos-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.os }}
    env: { LIBXML2_VERSION: 2.10.3, LIBXSLT_VERSION: 1.1.37, MACOSX_DEPLOYMENT_TARGET: 11.0 }

    steps:
    - name: "Debug matrix"
      run: echo "${{ toJSON(matrix) }}"
      shell: bash

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install MacOS dependencies
      if: startsWith(runner.os, 'macos-')
      run: |
        brew install automake libtool
        ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize

    - name: Install dependencies
      run: python -m pip install setuptools wheel -r requirements.txt

    - name: Cache [libs]
      uses: actions/cache@v3
      if: startsWith(runner.os, 'macos-')
      with:
        path: |
          libs/*.xz
          libs/*.gz
          libs/*.zip
        key: non-linux-libs

    - name: Build wheels
      run: make sdist wheel
      env: { STATIC_DEPS: true, RUN_TESTS: true }

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/lxml-*.whl

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.os }}
        path: dist/lxml-*.whl
        if-no-files-found: ignore
